detector:
  resolution:
    energy:
    - 40.0
    - 100.0
    - 662.0
    - 2000.0
    - 5000.0
    width:
    - 5.0
    - 7.5
    - 20.0
    - 33.0
    - 50.0
general:
  CheckForOverlaps: 1000 0.01
  DiscretizeHits: true
  Geometry: /home/laura/Simulation/MEGAlib/geo/BurstCubeCylinder.geo.setup
  PhysicsListEM: Livermore
  StoreCalibrate: true
  StoreOnlyEventsWithEnergyLoss: true
  StoreSimulationInfo: true
  Version: 1
run:
  azmax: 225
  azmin: 225
  aznumbins: 1
  basename: 225_100_30
  emax: 100
  emin: 100
  enumbins: 1
  simdir: /home/laura/Research/local_test/SmallSteps/finalTest/randomBursts/225_100_30
  srcdir: /home/laura/Research/local_test/SmallSteps/finalTest/randomBursts/225_100_30
  stdout_dir: /home/laura/Research/local_test/SmallSteps/finalTest/randomBursts/225_100_30
  zemax: 30
  zemin: 30
  zenumbins: 1
source:
  Beam: FarfieldPointSource
  Flux: 1000.0
  NTriggers: 1000
  ParticleType: 1
  name: FFPS
