detector:
  resolution:
    energy:
    - 40.0
    - 100.0
    - 662.0
    - 2000.0
    - 5000.0
    width:
    - 5.0
    - 7.5
    - 20.0
    - 33.0
    - 50.0
general:
  CheckForOverlaps: 1000 0.01
  DiscretizeHits: true
  Geometry: $BURSTCUBE/MEGAlib/geo/BurstCube_1Cylinder.geo.setup
  PhysicsListEM: Livermore
  StoreCalibrate: true
  StoreOnlyEventsWithEnergyLoss: true
  StoreSimulationInfo: true
  Version: 1
run:
  azmax: 0
  azmin: 0
  aznumbins: 1
  basename: ze
  emax: 1000
  emin: 100
  enumbins: 6
  simdir: /home/laura/data/final_test
  srcdir: /home/laura/data/final_test
  stdout_dir: /home/laura/data/final_test
  zemax: 15
  zemin: 15
  zenumbins: 1
source:
  Beam: FarfieldPointSource
  Flux: 1000.0
  NTriggers: 1000
  ParticleType: 1
  name: FFPS
