detector:
  resolution:
    energy:
    - 40.0
    - 100.0
    - 662.0
    - 2000.0
    - 5000.0
    width:
    - 5.0
    - 7.5
    - 20.0
    - 33.0
    - 50.0
general:
  CheckForOverlaps: 1000 0.01
  DiscretizeHits: true
  Geometry: /home/laura/Simulation/BurstCube/data/BurstCube_1Cylinder.geo.setup
  PhysicsListEM: Livermore
  StoreCalibrate: true
  StoreOnlyEventsWithEnergyLoss: true
  StoreSimulationInfo: true
  Version: 1
run:
  azmax: 60
  azmin: 0
  aznumbins: 3
  basename: test
  emax: 1000.0
  emin: 10.0
  enumbins: 3
  simdir: /home/laura/Simulation/BurstCube/data/test_sims/
  srcdir: /home/laura/Simulation/BurstCube/data/test_sims/
  stdout_dir: /home/laura/Simulation/BurstCube/data/test_sims/
  zemax: 60
  zemin: 0
  zenumbins: 3
source:
  Beam: FarfieldPointSource
  Flux: 1000.0
  NTriggers: 1000
  ParticleType: 1
  name: FFPS
